// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChoki2z9q9saSp5qCsIQ-L7uhOhGYDLaA',
    appId: '1:55886494004:web:d0e6c0c099c963d3324d61',
    messagingSenderId: '55886494004',
    projectId: 'cda-2023-2024',
    authDomain: 'cda-2023-2024.firebaseapp.com',
    storageBucket: 'cda-2023-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN3SwKULfRc5e0mdpkdmPvaFhB8fC0n-8',
    appId: '1:55886494004:android:41ced2d266605696324d61',
    messagingSenderId: '55886494004',
    projectId: 'cda-2023-2024',
    storageBucket: 'cda-2023-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD10Vn38hL2J_iGUPTS3u_9tmX27OTDiho',
    appId: '1:55886494004:ios:9c122972cf1a69b4324d61',
    messagingSenderId: '55886494004',
    projectId: 'cda-2023-2024',
    storageBucket: 'cda-2023-2024.appspot.com',
    iosBundleId: 'com.testfutter.testfluutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD10Vn38hL2J_iGUPTS3u_9tmX27OTDiho',
    appId: '1:55886494004:ios:756ea75bc8529ba5324d61',
    messagingSenderId: '55886494004',
    projectId: 'cda-2023-2024',
    storageBucket: 'cda-2023-2024.appspot.com',
    iosBundleId: 'com.testfutter.testfluutter.RunnerTests',
  );
}
